### PR TITLE
Update Roles and Role Handling (Issues 40, 45, 82)

### PR DESCRIPTION
**Pull request by spacehamster87**
* General
   * `My Jobs`-View now for every role and every user
   * Re-ordered fields in admin `addUser` card
       * Required `username (id)` now at the top, followed by `password`, optional fields afterwards.
   * Added some helper function to check for roles
      * `HasAnyRole(queryroles []string) bool`: User has at least one of the queried roles
      * `HasAllRoles(queryroles []string) bool`: User has *all* of the queried roles
      * `HasNotRoles(queryroles []string) bool`: User has *none* of the queried roles
      * `IsValidRole(role string) bool`: Given string matches valid role
   * List of valid roles for rendering selections in admin-config are now fetched from backend via new API-call (admins only)
   * Reworked frontend role-checks from "direct" bools (e.g. `isAdmin`) to "authLevels"
      * 0: Anonymous (unused)
      * 1: API
      * 2: User
      * 3: Manager
      * 4: Support
      * 5: Admin
    * Reworked repo.query.SecurityCheck()
* Adds role `manager`
   * Adds column `project` to `user` SQL table
   * Admins can assign/reset/remove ONE project-id to a manager-user in config interface
   * Managers will be able to see all jobs of assigned project (Filter added to GraphQL)
   * Managers will be able to see and use users-table, listing users of assigned project
   * Managers will be able to see and use all tags for assigned project
* Reworked role `support`
   * Supporters will be able to use most views equal to an admin user (= see all jobs, users, and tags)
   * Exceptions are:
     * `systems`-view not visible/usable (Draft @moebiusband73 )
     * `status`-view not visible/usable (Draft @moebiusband73 )
     * Admin-Config not accessible

<hr>

_Opened as draft pull request due to additional required 'project' column in SQL user table: Breaking change?_

PRs #80 and #81 probably need to be merged first, due to overlap.

### CODE REVIEW

**Comment by oscarminus** [comment]
I have one improvemend to the role manager: In our case, a manager could be a manager of multiple projects. So this shoud me a list of projects instead of one single project.

**Comment by spacehamster87** [comment]
* New column name in database changed from `project` to `projects` in latest commit
    * Was `project  varchar(255) DEFAULT NULL`
    * Is now `projects varchar(255) NOT NULL DEFAULT "[]"`

**Comment by spacehamster87** [comment]
Projects-Column now as "version 3" of the database migration pipelines

**Review by spacehamster87 — COMMENTED** [review]
Viewed / Checked all files: Minor issues will be fixed in next commt.

Afterwards, pull request seems ready for review.

**Comment by spacehamster87** [comment]
Final list of (updated) changes:

* General
   * `My Jobs`-View now for every role and every user
   * `user` role now has access to job-list
       * Only lists own jobs, but with addition of project filters  
   * Re-ordered fields in admin `addUser` card
       * Required `username (id)` now at the top, followed by `password`, optional fields afterwards.
   * Added some helper function to check for roles
      * `HasAnyRole(queryroles []string) bool`: User has at least one of the queried roles
      * `HasAllRoles(queryroles []string) bool`: User has *all* of the queried roles
      * `HasNotRoles(queryroles []string) bool`: User has *none* of the queried roles
      * `IsValidRole(role string) bool`: Given string matches valid role
   * List of valid roles for rendering selections in admin-config are now fetched from backend via new API-call (admins only)
   * Reworked frontend role-checks from "direct" bools (e.g. `isAdmin`) to "authLevels"
      * 0: Anonymous (unused)
      * 1: API
      * 2: User
      * 3: Manager
      * 4: Support
      * 5: Admin
    * Reworked repo.query.SecurityCheck()
* Adds role `manager`
   * Adds column `projects` to `user` SQL table
   * Admins can assign/reset/remove (multiple) project-id(s) to a manager-user in config interface
   * Managers will be able to see all jobs of assigned projects (Filter applied in backend)
   * Managers will be able to see and use users-table, listing users of assigned project
   * Managers will be able to see and use all tags for assigned project
* Reworked role `support`
   * Supporters will be able to use most views equal to an admin user (= see all jobs, users, and tags)
   * Exceptions are:
     * `systems`-view not visible/usable
     * `status`-view not visible/usable
     * Admin-Config not accessible
* Database migration to version 3: Adds `projects` columns to `users` table

**Review by moebiusband73 — COMMENTED** [review]
As discussed remove remove change in gitignore.

We should consider to replace the hardcoded role level with an enum.

Otherwise this looks very good!

**Pull request merged**
